baseURL = "https://kog.indrani.me"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Knowledge | Opportunity | Guidance"
[markup.goldmark.renderer]
unsafe = true
