author = "Themefisher"
contact_form_action = "#"
description = ""
logo = "images/logo_2-01.png"
logo_width = "200px"
social = []
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
